name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2, pull repo, and redeploy backend
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/healthcare-assistant
            git pull origin main
            cd backend
            docker-compose -f docker-compose.prod.yml down --rmi all --volumes --remove-orphans
            docker-compose -f docker-compose.prod.yml up -d --build
